default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zssn-api_development

test:
  <<: *default
  database: zssn-api_test

production:
  <<: *default
  database: zssn-api_production
  username: zssn-api
  password: <%= ENV['ZSSN-API_DATABASE_PASSWORD'] %>
